---
title: "Individual associations"
author: "Josh Alampi"
date: "2024-06-12"
output:
  html_document: default
  pdf_document: default
---

# load
```{r include=FALSE}
#clear workspace
rm(list=ls(all=TRUE))

# load packages and functions
source(here::here("libraries.R"))
source("functions/ggplot functions.R")
source("functions/analysis functions.R")

data <- read.csv("//ais-fs1.sfu.ca/home2/Redirected_Profiles/jalampi/Desktop/MIREC loader 2022/clean data/MIREC data_mixtures.csv") %>% 
  filter(is.na(srs) == F) %>% 
  clean_data()

chemical_info <- readxl::read_xlsx(here::here("data", "chemical info.xlsx"))

chemicals <-(c("arsenic.t1.res", "cadmium.t1.res", "lead.t1.res", "mercury.t1.res", 
               "bbhc.t1.res", "dde.t1.res", "oxychlor.t1.res", "transnona.t1.res",
               "pfhxs.t1.res", "pfos.t1.res", "pfoa.t1.res",
               "pcb118.t1.res", "pcb138.t1.res", "pcb153.t1.res", "pcb180.t1.res",
               "bde47.t1.res"))

num_chems <- length(chemicals)
```

# Prep
```{r}
alpha <- 0.05

# make container
table_indiv <- setNames(data.frame(matrix(data = NA, nrow = num_chems * 2, ncol = 7)), #make dataframe
                                        c("x_name",
                                          "beta", "lb", "ub", 
                                          "p", "transformation", "class")) #set column names
```


## Implement MICE
```{r}
m <- 10

imputed_data <- mice(data, m = m, printFlag = F, seed = 1010)
```

# perform analysis- with MICE
```{r include=FALSE}
for (i in 1:num_chems) {
  
  # Extract information about the ith chemical
  name_x <- chemical_info$name[i]
  class <- chemical_info$Class[i]
  
  # Make lists to store results for each individual chemical
  all_k_log2_models <- list()
  all_k_quartile_models <- list()
  
  for (k in 1:m){
    
    # Extract the kth imputed dataset
    imputed_data_k <- complete(imputed_data, action = k)
    
    # Select the ith chemical
    x <- imputed_data_k[,chemicals[i]]
    
    # Transform the chemical
    cut <- quantile(x, probs = c(0.25, 0.5, 0.75))
    
    imputed_data_k <- imputed_data_k %>% 
      mutate(log2_x = log2(x)) %>% 
      mutate(quarile_x = case_when(x < cut[1] ~ 1,
                                   x >= cut[1] & x < cut[2] ~ 2,
                                   x >= cut[2] & x < cut[3] ~ 3,
                                   x >= cut[3] ~ 4))
    
    # log2(x) vs Y analysis
    model_log2 <- lm(srs ~ log2_x + sex2+ income4+ edu4+ living.status2+ home.score+ race.white2+ mom.age+ parity3+ city6+ year.enroll4 + smoker2 + srs.age + fol.intake3, data = imputed_data_k)
    
    # Quartile(x) vs Y analysis
    model_quartile <- lm(srs ~ quarile_x + sex2+ income4+ edu4+ living.status2+ home.score+ race.white2+ mom.age+ parity3+ city6+ year.enroll4 + smoker2 + srs.age + fol.intake3, data = imputed_data_k)
    
    # Store results for each imputed dataset
    all_k_log2_models[[k]] <- model_log2
    all_k_quartile_models[[k]] <- model_quartile
  }
  
  # Pool k models
  pooled_log2_results <- pool(all_k_log2_models)
  pooled_quartile_results <- pool(all_k_quartile_models)
  
  # Store results
  ## log2 model
  coef <- summary(pooled_log2_results)[2,]
  t <- qt(1 - (alpha / 2), as.numeric(coef[5]))
  
  table_indiv[i * 2 - 1, 1] <- name_x
  table_indiv[i * 2 - 1, 2] <- coef[2]                  # beta
  table_indiv[i * 2 - 1, 3] <- coef[2] - (coef[3] * t)  # lb
  table_indiv[i * 2 - 1, 4] <- coef[2] + (coef[3] * t)  # ub
  table_indiv[i * 2 - 1, 5] <- coef[6]                  # p 
  table_indiv[i * 2 - 1, 6] <- "Differenceᵃ in SRS-2 score per two-fold \nincrease in chemical concentration"
  table_indiv[i * 2 - 1, 7] <- class
  
  
  # Quartile model
  coef <- summary(pooled_quartile_results)[2,]
  t <- qt(1 - (alpha / 2), as.numeric(coef[5]))
  
  table_indiv[i * 2, 1] <- name_x
  table_indiv[i * 2, 2] <- coef[2]                  # beta
  table_indiv[i * 2, 3] <- coef[2] - (coef[3] * t)  # lb
  table_indiv[i * 2, 4] <- coef[2] + (coef[3] * t)  # ub
  table_indiv[i * 2, 5] <- coef[6]                  # p 
  table_indiv[i * 2, 6] <- "Differenceᵃ in SRS-2 score per one-quartile \nincrease in chemical concentration"
  table_indiv[i * 2, 7] <- class

}
```

# make fig
```{r}
library("scales")
reverselog_trans <- function(base = exp(1)) {
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv, 
              log_breaks(base = base), 
              domain = c(1e-100, Inf))
}
```


```{r}
fig_indiv <- table_indiv %>% 
  # Flag the stronger/ more notable associations. Will add text for them. 
  mutate(flag = as.factor(ifelse(p <= 0.2 | abs(beta) > 0.25, 1, 0))) %>% 
  
  # Make figure
  ggplot(aes(colour = class)) + 
  geom_jitter(aes(x = beta, y = p)) + 
  geom_label_repel(aes(x = beta, y = p, label = x_name, alpha = flag), 
            show.legend = F,
            hjust = 0.5, vjust = 0.5
            ) +
            # position = position_jitterdodge(jitter.width = 0.1,
            #                                 jitter.height = 0.1,
            #                                 dodge.width = 0.2,
            #                                 seed = 1)) + # settings for dispersing text (make it readable)
  facet_wrap(~ transformation) +
  
  # Adjust
  gg_aesthetic(yint = 0.05, xint = 0, alpha_vec = c(0,1)) +
  scale_y_continuous(transform = reverselog_trans(),
                     breaks = c(0.001, 0.01, 0.05, 0.1, 0.5, 1),
                     limits = c(1, 0.0025)) +
  scale_x_continuous(breaks = c(-1, -0.5, 0, 0.5, 1), 
                     limits = c(-1, 1)) +
  
  labs(x = "Point estimate (β)", y = "p-value", colour = "Chemical class") +
  gg_legend(2, margin = 0) + # modify legend
  
  # tweaks
  gg_text(7.5, 10) +
  guides(color = guide_legend(nrow = 3))

fig_indiv
```


# Save
```{r include=FALSE}
my_ggsave(fig_indiv, "output/", "fig_individual associations", T, "analysis/archive/", height = 5)
my_write.csv(table_indiv, "output/analysis/", "individual associations", T, "archive/")
```

```{r}

```









