---
title: "indiv associations_with MICE_fol mod"
author: "Josh Alampi"
date: "2025-03-20"
output: html_document
---


# load
```{r include=FALSE}
#clear workspace
rm(list=ls(all=TRUE))

# load packages and functions
source(here::here("libraries.R"))
source("functions/ggplot functions.R")
source("functions/analysis functions.R")

data_all <- read.csv("//ais-fs1.sfu.ca/home2/Redirected_Profiles/jalampi/Desktop/MIREC loader 2022/clean data/MIREC data_mixtures.csv") %>% 
  clean_data(clean_city = F)

chemical_info <- readxl::read_xlsx(here::here("data", "chemical info.xlsx"))
```

# IPW
```{r}
data_all2 <- ipw_analysis(data_all, m_ipw = 10)
```

# Post-IPW cleaning
Exclude participants without an SRS score and fix the city variable now that only participants from 6 cities are left
```{r}
data <- data_all2 %>% 
  filter(is.na(srs) == F) %>% 
  clean_city()
```

# Prep
## identify chemicals and confounders
```{r include=FALSE}
chemicals <-(c("arsenic.t1.res", "cadmium.t1.res", "lead.t1.res", "mercury.t1.res", 
               "bbhc.t1.res", "dde.t1.res", "oxychlor.t1.res", "transnona.t1.res",
               "pfhxs.t1.res", "pfos.t1.res", "pfoa.t1.res",
               "pcb118.t1.res", "pcb138.t1.res", "pcb153.t1.res", "pcb180.t1.res",
               "bde47.t1.res"))

num_chems <- length(chemicals)

confounder_names <- c("sex2", "income4", "edu4", "living.status2", "home.score", "race.white2", 
                      "mom.age", "parity3", "year.enroll4", "srs.age", "city6", "fol.intake3", "smoker2")

confounder_names_folint <- c("sex2", "income4", "edu4", "living.status2", "home.score", "race.white2", 
                             "mom.age", "parity3", "year.enroll4", "srs.age", "city6", "smoker2")

list_level_names <- list(c("400-1000", "<400", ">1000"),
                         c("10th-80th %ile", "<10th %ile", ">80th %ile"))
```


```{r}
# # log2 transform all chemicals
# data <- data %>%
#   mutate(across(chemicals, log2))

# # quartile transform all chemicals
# transform_quartile <- function(x) {
#   cut <- quantile(x, probs = c(0.25, 0.5, 0.75), na.rm = T)
# 
#   new_x <- case_when(x < cut[1] ~ 1,
#                                    x >= cut[1] & x < cut[2] ~ 2,
#                                    x >= cut[2] & x < cut[3] ~ 3,
#                                    x >= cut[3] ~ 4)
# }
# data <- data %>%
#   mutate(across(chemicals, transform_quartile))

```


## Implement MICE
```{r}
m <- 10
variables_to_ignore <- c("included", "pscore_mice", "ipw", "ipw_stabilized")

# Generate the default predictor matrix
pred <- make.predictorMatrix(data)

# Set the selected variables to 0 in all rows (prevent them from being used as predictors)
pred[, variables_to_ignore] <- 0

imputed_data <- mice(data, predictorMatrix = pred, m = m, printFlag = F, seed = 1010)

m <- 10
imputed_data <- mice(data, m = m, printFlag = F, seed = 1010)
```

## Implement post-MICE transformations
Transform all chemical concentrations
```{r}
## make a function for quaritle transformations:
# transform_quartile <- function(x) {
#   # Compute quartiles safely
#   cut <- quantile(x, probs = c(0.25, 0.5, 0.75), na.rm = TRUE)
# 
#   # Apply transformation with NA handling
#   new_x <- case_when(
#     # is.na(x) ~ NA_real_,  # Preserve NA values
#     x < cut[1] ~ 1,
#     x >= cut[1] & x < cut[2] ~ 2,
#     x >= cut[2] & x < cut[3] ~ 3,
#     x >= cut[3] ~ 4,
#     # TRUE ~ NA_real_  # Catch unexpected cases
#   )
# 
#   return(as.numeric(new_x))
# }

## Make a long version of the dataset (includes all imputed datasets amended together)
completed_data <- complete(imputed_data, action = "long", include = TRUE)

## Apply transformation to the imputed values
# transformed_data <- completed_data %>%
#   mutate(across(chemicals, transform_quartile))
transformed_data <- completed_data %>%
  mutate(across(chemicals, log2))

## Convert back to a `mids` object using `as.mids()`
imputed_transformed_data <- as.mids(transformed_data)

# check
hist(transformed_data$dde.t1.res[transformed_data$.imp ==1], breaks = 40)  # imputed and transformed. looks as expected
hist(data$dde.t1.res, breaks = 40)  # Original data


```

# perform analysis- with MICE

## No mod
```{r include=FALSE}

for (i in 1:num_chems) {
  # Extract information about the ith chemical
  this_chemical <- chemicals[i]
  name_x <- chemical_info$name[i]
  class <- chemical_info$Class[i]
  
  # this_formula <- as.formula(paste(y, " ~ ", 
  #                                    paste(c(this_chemical, confounder_names), collapse = "+")))
  
  # make model
  model_mice <- with(imputed_transformed_data, lm(as.formula(paste("srs", " ~ ", 
                                                                   paste(c(this_chemical, confounder_names), collapse = "+")))
                                                  ,weights = ipw_stabilized))
  
  # Store results
  table_tmp <- get_mice_res(model_mice, name_x = name_x, round = 4)
  
  ## Store results
  ifelse(i == 1, 
         
         # if this is the first iteration:
         table_noint <- table_tmp, # Store results in a new table 
         
         # if this is not the first iteration:
         table_noint <- rbind(table_noint,  table_tmp) # Amend results to the existing table
         )
}

table_noint
```

## assessing modification
```{r}

for (i in 1:num_chems) {
  # Extract information about the ith chemical
  this_chemical <- chemicals[i]
  name_x <- chemical_info$name[i]
  class <- chemical_info$Class[i]
  
  # fa supp mod------------------------------------------------------------
  ## make model
  model_mice_int <- with(imputed_transformed_data, lm(as.formula(paste("srs", " ~ ", 
                                                           paste(c(this_chemical, 
                                                                   "fol.intake3",
                                                                   paste0(this_chemical, ":fol.intake3"), 
                                                                   confounder_names_folint), 
                                                                   collapse = "+"))),
                                                      weights = ipw_stabilized))
                         
  ## Get results
  table_tmp <- get_mice_res_intcat3(model_mice_int, name_z = "fol.intake3", name_x = name_x, 
                              level_names = list_level_names[[1]], round = 4)
  
  ## Store results
  ifelse(i == 1, 
         
         # if this is the first iteration:
         table_fa_int <- table_tmp, # Store results in a new table 
         
         # if this is not the first iteration:
         table_fa_int <- rbind(table_fa_int,  table_tmp) # Amend results to the existing table
         )
  
  # Plasma total folate mod------------------------------------------------------------
  ## make model
  model_mice_int <- with(imputed_transformed_data, lm(as.formula(paste("srs", " ~ ", 
                                                           paste(c(this_chemical, 
                                                                   "pl_fol3.t1",
                                                                   paste0(this_chemical, ":pl_fol3.t1"), 
                                                                   confounder_names_folint), 
                                                                   collapse = "+"))),
                                                      weights = ipw_stabilized))
                         
  ## Get results
  table_tmp <- get_mice_res_intcat3(model_mice_int, name_z = "pl_fol3.t1", name_x = name_x, 
                              level_names = list_level_names[[2]], round = 4)
  
  ## Store results
  ifelse(i == 1, 
         
         # if this is the first iteration:
         table_plfol_int <- table_tmp, # Store results in a new table 
         
         # if this is not the first iteration:
         table_plfol_int <- rbind(table_plfol_int,  table_tmp) # Amend results to the existing table
         )
  
}

table_fa_int
table_plfol_int

```
# Put together
```{r}
# table_indiv <- rbind(rbind(table_noint, table_fa_int), table_plfol_int)
table_indiv <- rbind(table_noint, table_fa_int) %>% 
  rbind(., table_plfol_int) 
```

# Save
```{r include=FALSE}
my_write.csv(table_indiv, "output/analysis/", "individual associations_int_IPW", T, "archive/")
```

```{r}

```









