---
title: "wqsr analysis_with MICE"
author: "Josh Alampi"
date: "2024-07-11"
output: html_document
---



# load 
```{r}
#clear workspace
rm(list=ls(all=TRUE))

# load packages and functions
source("libraries.R", echo = T)
source("functions/analysis functions.R")

# Load MIREC data
data <- read.csv("//ais-fs1.sfu.ca/home2/Redirected_Profiles/jalampi/Desktop/MIREC loader 2022/clean data/MIREC data_mixtures.csv") %>% 
  filter(is.na(srs) == F) %>% 
  clean_data()

```


## Implement MICE
```{r}
m <- 10

imputed_data <- mice(data, m = m, printFlag = F, seed = 1010)
```


# Prep
```{r}
chemical_names_list <- list(c("arsenic.t1.res", "cadmium.t1.res", "lead.t1.res", "mercury.t1.res"),
                            c("bbhc.t1.res", "dde.t1.res", "oxychlor.t1.res", "transnona.t1.res"),
                            c("pfhxs.t1.res", "pfos.t1.res", "pfoa.t1.res"),
                            c("pcb118.t1.res", "pcb138.t1.res","pcb153.t1.res", "pcb180.t1.res"),
                            # c("bde47.t1.res"),
                            c("bbhc.t1.res", "dde.t1.res", "oxychlor.t1.res", "transnona.t1.res",
                              "pfhxs.t1.res", "pfos.t1.res", "pfoa.t1.res",
                              "pcb118.t1.res", "pcb138.t1.res","pcb153.t1.res", "pcb180.t1.res",
                              "bde47.t1.res"))

confounder_names <- c("sex2", "income4", "edu4", "living.status2", "home.score", "race.white2", 
                      "mom.age", "parity3", "year.enroll4", "srs.age", "city6", "fol.intake3", "smoker2")

mixture_names <- c("Metals", "OC Pesticides", "PFAS", "PCBs", "All POPs")
# conf <- "+ sex2+ income4+ edu4+ living.status2+ home.score+ race.white2+ mom.age+ parity3+ city10+ year.enroll4 + smoker2 + srs.age"


formula <- as.formula(paste0("srs ~ wqs + ", paste(confounder_names, collapse = " + ")))
```

Make containers
```{r}
all_pos_weights <- list(); all_neg_weights <- list()
all_pooled_pos_weights <- list(); all_pooled_neg_weights <- list()

table_wqs <- setNames(data.frame(matrix(data = NA, nrow = length(chemical_names_list), ncol = 9)),
                      c("mixture_name", "beta_pos", "lb_pos", "ub_pos", "se_pos", 
                        "beta_neg", "lb_neg", "ub_neg", "se_neg")) #set column names
```

# Analysis
```{r}
b <- 1000 # number of bootstraps

for (i in 1:length(chemical_names_list)) {
  
  this_chemical_names <- chemical_names_list[[i]]
  
  # Loop through 'm' imputed datasets ----
      
  pos_results_all_k_datasets <- list() # I need these lists to reset for every new i-loop
  neg_results_all_k_datasets <- list() 
  pos_weights_all_k_datasets <- list()
  neg_weights_all_k_datasets <- list()
  
  for (k in 1:m){
    print(paste0("Mixture ", i, " of ", length(chemical_names_list),
                 ", imputation ", k, " of ", m))
    
    # Extract the kth imputed dataset
    imputed_data_k <- complete(imputed_data, action = k)
    
    # Fit the model with the kth imputed dataset
    pos_wqs_fit <- gwqs(formula, 
                        b1_pos = T, b_constr = T, # Weights are positive
                        q = 4, mix_name = this_chemical_names, data = imputed_data_k,
                        validation = 0.6, b = b, family = "gaussian", seed = 1)

    neg_wqs_fit <- gwqs(formula, 
                        b1_pos = F, b_constr = T, # Weights are negative
                        q = 4, mix_name = this_chemical_names, data = imputed_data_k,
                        validation = 0.6, b = b, family = "gaussian", seed = 1)
      
    # Save the fitted model
    pos_results_all_k_datasets[[k]] <- pos_wqs_fit
    neg_results_all_k_datasets[[k]] <- neg_wqs_fit
    
    # Prepare the weights (arrange in specific order, add mixture name, imputation number)
    weights_pos <- arrange(pos_wqs_fit$final_weights, match(mix_name, this_chemical_names)) %>% 
      mutate(mixture_name = mixture_names[i]) %>% 
      mutate(imputation_number = k)
    
    weights_neg <- arrange(neg_wqs_fit$final_weights, match(mix_name, this_chemical_names)) %>% 
      mutate(mixture_name = mixture_names[i]) %>% 
      mutate(imputation_number = k)
    
    # Save the weights for each imputed dataset
    pos_weights_all_k_datasets[[k]] <- weights_pos
    neg_weights_all_k_datasets[[k]] <- weights_neg
    
  }
  
  # Pool results
  pos_pooled_results <- MIcombine(pos_results_all_k_datasets)
  pos_summary <- summary(pos_pooled_results)
  
  neg_pooled_results <- MIcombine(neg_results_all_k_datasets)
  neg_summary <- summary(neg_pooled_results)
  
  
  # Store positive results
  beta_pos <- pos_summary[2, 1]
  lb_pos <- pos_summary[2, 3]
  ub_pos <- pos_summary[2, 4]
  se_pos <- pos_summary[2, 2]
  
  table_wqs[i, 1] <- mixture_names[i]                     # Mixture name
  table_wqs[i, 2] <- round(beta_pos, 2)                   # beta_pos
  table_wqs[i, 3] <- round(lb_pos, 2)                     # lb_pos
  table_wqs[i, 4] <- round(ub_pos, 2)                     # ub_pos
  table_wqs[i, 5] <- round(se_pos, 2)                     # se_pos
  
  # Store negative results
  beta_neg <- neg_summary[2, 1]
  lb_neg <- neg_summary[2, 3]
  ub_neg <- neg_summary[2, 4]
  se_neg <- neg_summary[2, 2]
  
  table_wqs[i, 6] <- round(beta_neg, 2)                   # beta_neg
  table_wqs[i, 7] <- round(lb_neg, 2) # lb_neg
  table_wqs[i, 8] <- round(ub_neg, 2) # ub_neg
  table_wqs[i, 9]<- round(se_neg, 2)                     # se_neg
  
  # Store weights
  pos_df_weights <- bind_rows(pos_weights_all_k_datasets)
  neg_df_weights <- bind_rows(neg_weights_all_k_datasets)
  
  # Pool weights
  pos_pooled_weights <- pos_df_weights %>% 
    group_by(mix_name, mixture_name) %>% 
    summarize(ave_weight = mean(mean_weight)) %>% # Averaging the weights across all multiply imputed datasets
    arrange(match(mix_name, this_chemical_names)) # Put chemicals in the desired order
  
  neg_pooled_weights <- neg_df_weights %>% 
    group_by(mix_name, mixture_name) %>% 
    summarize(ave_weight = mean(mean_weight)) %>% # Averaging the weights across all multiply imputed datasets
    arrange(match(mix_name, this_chemical_names)) # Put chemicals in the desired order
  
  # Store weights
  all_pos_weights[[i]] <- pos_df_weights
  all_neg_weights[[i]] <- neg_df_weights
  
  all_pooled_pos_weights[[i]] <- pos_pooled_weights
  all_pooled_neg_weights[[i]] <- neg_pooled_weights
  
}

table_wqs
```

# Clean the weights
```{r}
# Convert list to dataframe
df_all_pos_weights <- as.data.frame(do.call(rbind, all_pos_weights))
df_all_neg_weights <- as.data.frame(do.call(rbind, all_neg_weights))

df_all_pos_weights
df_all_neg_weights
```

```{r}
# rename
df_all_pos_weights <-  df_all_pos_weights %>% 
  rename(mean_weight_pos = mean_weight) 

df_all_neg_weights <-  df_all_neg_weights %>% 
  rename(mean_weight_neg = mean_weight)

# merge
## Rearranging in the following order: mixture_name, mix_name (chemical name), pos weight, neg weight, imputation number
df_weights_all <- cbind(df_all_pos_weights, df_all_neg_weights)[,c(3, 1, 2, 6, 4)]

```

# Clean the pooled weights
```{r}
# Convert list to dataframe
df_all_pooled_pos_weights <- as.data.frame(do.call(rbind, all_pooled_pos_weights))
df_all_pooled_neg_weights <- as.data.frame(do.call(rbind, all_pooled_neg_weights))

df_all_pooled_pos_weights
df_all_pooled_neg_weights
```


# merge
```{r}
# rename
df_all_pooled_pos_weights <-  df_all_pooled_pos_weights %>% 
  rename(mean_weight_pos = ave_weight) 

df_all_pooled_neg_weights <-  df_all_pooled_neg_weights %>% 
  rename(mean_weight_neg = ave_weight)

# merge
## Rearranging in the following order: mixture_name, mix_name (chemical name), pos weight, neg weight, imputation number
df_pooled_weights_all <- cbind(df_all_pooled_pos_weights, df_all_pooled_neg_weights)[,c(2, 1, 3, 6)]

```

# Save
```{r}
my_write.csv(table_wqs, "output/analysis/", "raw res_wqs") # results
my_write.csv(df_weights_all, "output/analysis/", "raw weights_wqs") # weights
my_write.csv(df_pooled_weights_all, "output/analysis/", "raw pooled weights_wqs") # pooled weights

```





























```{r}

```

